const state={catalog:null,cart:[]};
const $=s=>document.querySelector(s);
const money=v=>v==null?'يحتاج تأكيد':`${v} ₪`;
async function init(){state.catalog=await fetch('./catalog.json').then(r=>r.json());renderMenu();renderCart();}
function renderMenu(){const grid=$('#menuGrid'); grid.innerHTML=state.catalog.products.map(p=>`<article class="product"><span class="product-cat">${p.category}</span><h3>${p.name}</h3><p>${p.nameEn}</p><strong>${money(p.price)}</strong><button class="button small-button" data-add="${p.id}" ${p.price==null?'disabled':''}>${p.price==null?'السعر قيد التحقق':'أضف للسلة'}</button></article>`).join('');grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));}
function add(id){const p=state.catalog.products.find(x=>x.id===id);const item=state.cart.find(x=>x.id===id);item?item.qty++:state.cart.push({id,qty:1});renderCart();toast(`أضيف ${p.name} إلى السلة`);}
function renderCart(){const items=$('#cartItems');$('#cartCount').textContent=state.cart.reduce((n,x)=>n+x.qty,0);items.innerHTML=state.cart.length?state.cart.map(x=>{const p=state.catalog.products.find(y=>y.id===x.id);return `<div class="cart-item"><div><b>${p.name}</b><small>${money(p.price)}</small></div><div class="qty"><button data-dec="${p.id}">−</button><span>${x.qty}</span><button data-inc="${p.id}">+</button></div></div>`}).join(''):'<p class="empty">السلة فارغة.</p>';items.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{state.cart.find(x=>x.id===b.dataset.inc).qty++;renderCart()});items.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const i=state.cart.findIndex(x=>x.id===b.dataset.dec);state.cart[i].qty--;if(state.cart[i].qty<1)state.cart.splice(i,1);renderCart()});const total=state.cart.reduce((n,x)=>{const p=state.catalog.products.find(y=>y.id===x.id);return n+(p.price||0)*x.qty},0);$('#cartTotal').textContent=`${total} ₪`}
function answer(q){const s=q.toLowerCase();const p=state.catalog.products.find(x=>s.includes(x.name.toLowerCase())||s.includes(x.nameEn.toLowerCase()));if(/سعر|بكم|كم/.test(s)&&p)return p.price?`سعر ${p.name} هو ${p.price} شيكل.`:`سعر ${p.name} غير موثق بعد.`;if(/قائمة|منتج|بيتزا/.test(s))return `لدينا ${state.catalog.products.filter(x=>x.price!=null).map(x=>`${x.name} (${x.price}₪)`).join('، ')}. المنتجات الأخرى تحتاج تأكيد السعر.`;if(/توصيل|يوصل|متى|ساعات|مفتوح|عنوان|هاتف/.test(s))return 'هذه المعلومة غير موثقة بعد. سأرفعها للمراجعة البشرية ولا أستطيع اختلاقها.';return 'لم أجد إجابة موثقة. يمكن للمسؤول مراجعة هذا السؤال قبل الرد.'}
$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput');const q=input.value.trim();if(!q)return;$('#chatLog').insertAdjacentHTML('beforeend',`<div class="bubble user">${escapeHtml(q)}</div><div class="bubble agent">${answer(q)}</div>`);input.value='';};
$('#cartButton').onclick=()=>{$('#cartDrawer').setAttribute('aria-hidden','false');$('#cartDrawer').classList.add('open')};$('#closeCart').onclick=()=>{$('#cartDrawer').setAttribute('aria-hidden','true');$('#cartDrawer').classList.remove('open')};$('#orderForm').onsubmit=e=>{e.preventDefault();if(!state.cart.length)return toast('أضف منتجاً مسعراً أولاً');toast('تم تجهيز الطلب للمراجعة البشرية فقط');e.target.reset()};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}init();
