import { getWorkCompassOutput, workCompassAiRoles, workCompassNeeds, workCompassVerifications, type WorkCompassAiRole, type WorkCompassNeed, type WorkCompassVerification } from "@/lib/workCompass";
import { cn } from "@/lib/utils";
import { growthJourneyHref, sensePortalHref } from "@/lib/sensePortalRoute";
import { ArrowLeft, Bot, CheckCircle2, ClipboardCheck, Compass, Copy, RotateCcw, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

export default function WorkCompass() {
  const [need, setNeed] = useState<WorkCompassNeed | null>(null);
  const [aiRole, setAiRole] = useState<WorkCompassAiRole | null>(null);
  const [verification, setVerification] = useState<WorkCompassVerification | null>(null);
  const [copied, setCopied] = useState(false);
  const output = useMemo(() => need && aiRole && verification ? getWorkCompassOutput({ need, aiRole, verification }) : null, [need, aiRole, verification]);

  function reset() { setNeed(null); setAiRole(null); setVerification(null); setCopied(false); }
  async function copyCard() {
    if (!output) return;
    const text = [output.title, `المخرج: ${output.outcome}`, `الخطوة التالية: ${output.nextStep}`, ...output.checklist.map((item) => `- ${item}`)].join("\n");
    await navigator.clipboard?.writeText(text);
    setCopied(true);
  }

  return <main dir="rtl" className="min-h-screen bg-[#f8f7f0] text-[#173b3a]"><div className="mx-auto max-w-7xl px-5 pb-16 pt-5 lg:px-8">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#173b3a]/15 pb-5"><Link href={sensePortalHref} className="inline-flex items-center gap-3 rounded-xl font-extrabold hover:text-[#95691f]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#173b3a] text-[#f5cd74]"><Compass size={22} /></span><span><b className="block text-lg">SENSE / بوصلة العمل</b><small className="font-bold text-[#5b746d]">حاجة واضحة · ذكاء اصطناعي · تدقيق · مخرج قابل لإعادة الاستخدام</small></span></Link><button type="button" onClick={reset} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[#173b3a]/20 px-3 text-sm font-extrabold text-[#426057] hover:border-[#a87521]"><RotateCcw size={16} />ابدأ من جديد</button></header>
    <section className="grid gap-8 py-12 lg:grid-cols-[1.12fr_.88fr] lg:items-end"><div><p className="inline-flex items-center gap-2 rounded-full bg-[#e8cf98]/45 px-3 py-1.5 text-xs font-extrabold text-[#705019]"><Bot size={14} />ميزة عمل حية بلا حساب</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-[1.14] tracking-tight sm:text-6xl">ارسم الحاجة والطريق، ثم اجعل الذكاء الاصطناعي <span className="text-[#a87521]">يخدم قرارك.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#58716a]">البوصلة تبني بطاقة عمل قصيرة: حاجة حقيقية، دور محدد للذكاء الاصطناعي، طريقة تحقق، ومخرج يستطيع شخص آخر مراجعته أو البناء عليه.</p></div><aside className="rounded-[2rem] bg-[#173b3a] p-7 text-white"><ClipboardCheck className="text-[#f5cd74]" size={24} /><h2 className="mt-5 text-2xl font-extrabold">من سرعة إلى قدرة</h2><p className="mt-3 leading-7 text-[#c9ddd5]">السرعة مهمة. القيمة تظهر حين يبقى الإنسان مالك الغاية، ومراجع المصدر، وصاحب القرار في اعتماد المخرج.</p></aside></section>
    <section aria-labelledby="steps-title"><div><p className="text-sm font-extrabold text-[#a87521]">01–03 · ابنِ بطاقتك</p><h2 id="steps-title" className="mt-1 text-3xl font-extrabold">اختر الحاجة والدور وطريقة التحقق.</h2></div><div className="mt-7 grid gap-6 xl:grid-cols-3">
      <article className="rounded-[1.75rem] border border-[#173b3a]/15 bg-white p-6"><p className="text-sm font-extrabold text-[#9b6c20]">01 · الحاجة</p><h3 className="mt-2 text-xl font-extrabold">ماذا تريد أن تدفعه خطوة؟</h3><div className="mt-5 grid gap-3">{workCompassNeeds.map((item) => <button key={item.id} type="button" onClick={() => setNeed(item.id)} className={cn("rounded-2xl border p-4 text-right transition-colors", need === item.id ? "border-[#a87521] bg-[#fff7e6]" : "border-[#173b3a]/15 hover:border-[#a87521]/55")}><b>{item.label}</b><span className="mt-1 block text-sm leading-6 text-[#607971]">{item.prompt}</span></button>)}</div></article>
      <article className="rounded-[1.75rem] border border-[#173b3a]/15 bg-white p-6"><p className="text-sm font-extrabold text-[#9b6c20]">02 · دور الأداة</p><h3 className="mt-2 text-xl font-extrabold">أين تساعدك دون أن تحل محل حكمك؟</h3><div className="mt-5 grid gap-3">{workCompassAiRoles.map((item) => <button key={item.id} type="button" onClick={() => setAiRole(item.id)} className={cn("rounded-2xl border p-4 text-right transition-colors", aiRole === item.id ? "border-[#a87521] bg-[#fff7e6]" : "border-[#173b3a]/15 hover:border-[#a87521]/55")}><b>{item.label}</b><span className="mt-1 block text-sm leading-6 text-[#607971]">{item.detail}</span></button>)}</div></article>
      <article className="rounded-[1.75rem] border border-[#173b3a]/15 bg-white p-6"><p className="text-sm font-extrabold text-[#9b6c20]">03 · التحقق</p><h3 className="mt-2 text-xl font-extrabold">كيف يصبح المخرج جديرًا بالثقة؟</h3><div className="mt-5 grid gap-3">{workCompassVerifications.map((item) => <button key={item.id} type="button" onClick={() => setVerification(item.id)} className={cn("rounded-2xl border p-4 text-right transition-colors", verification === item.id ? "border-[#a87521] bg-[#fff7e6]" : "border-[#173b3a]/15 hover:border-[#a87521]/55")}><b>{item.label}</b><span className="mt-1 block text-sm leading-6 text-[#607971]">{item.detail}</span></button>)}</div></article>
    </div></section>
    {output && <section className="mt-8 rounded-[2rem] border border-emerald-700/20 bg-[#e5f0e7] p-7 sm:p-9" aria-live="polite"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-extrabold text-[#8e651e]">بطاقة عملك جاهزة</p><h2 className="mt-2 text-3xl font-extrabold">{output.title}</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-[#4d695f]">المخرج الأول: <b>{output.outcome}</b>. {output.nextStep}</p></div><CheckCircle2 className="text-emerald-700" size={31} /></div><div className="mt-7 grid gap-3 md:grid-cols-2">{output.checklist.map((item) => <p key={item} className="rounded-2xl bg-white/75 p-4 text-sm font-bold leading-6 text-[#466259]">{item}</p>)}</div><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={copyCard} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#173b3a] px-4 text-sm font-extrabold text-white"><Copy size={16} />{copied ? "نُسخت البطاقة" : "انسخ بطاقة العمل"}</button><Link href={growthJourneyHref} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#173b3a]/20 px-4 text-sm font-extrabold text-[#35574f]">حوّلها إلى رحلة نمو <ArrowLeft size={16} /></Link></div></section>}
    <section className="mt-12 grid gap-4 border-t border-[#173b3a]/15 pt-10 md:grid-cols-3"><article className="rounded-[1.5rem] bg-[#173b3a] p-6 text-white"><ShieldCheck className="text-[#f5cd74]" size={22} /><h2 className="mt-5 text-xl font-extrabold">خصوصيتك في يدك</h2><p className="mt-3 leading-7 text-[#c9ddd5]">لا تطلب البوصلة اسمًا أو هاتفًا أو حسابًا، ولا تحفظ بطاقة عملك في قاعدة بيانات.</p></article><article className="rounded-[1.5rem] border border-[#173b3a]/15 bg-white p-6"><Bot className="text-[#a87521]" size={22} /><h2 className="mt-5 text-xl font-extrabold">الأداة لا تقرر وحدها</h2><p className="mt-3 leading-7 text-[#58716a]">حدد الغاية والمصدر وصاحب المراجعة قبل أن تحول أي مخرج إلى قرار أو ادعاء عام.</p></article><article className="rounded-[1.5rem] border border-[#173b3a]/15 bg-white p-6"><Compass className="text-[#a87521]" size={22} /><h2 className="mt-5 text-xl font-extrabold">مخرج قابل للتعاون</h2><p className="mt-3 leading-7 text-[#58716a]">انسخ البطاقة وشاركها مع فريق أو مراجع عندما تحتاج أدوارًا متكاملة أو خبرة إضافية.</p></article></section>
  </div></main>;
}
