import { earnedValueDestinations, earnedValueRules, resolveDestination, saveDefaultDestination, type DestinationId, type EarnedValueKind } from "@/lib/loyaltyModel";
import { sensePortalHref } from "@/lib/sensePortalRoute";
import { cn } from "@/lib/utils";
import { ArrowLeft, BadgeCheck, CircleDollarSign, Gift, LockKeyhole, PhoneOff, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const options: Array<{ id: EarnedValueKind; icon: typeof Sparkles; label: string }> = [
  { id: "points", icon: Sparkles, label: "نقاط تقدير" }, { id: "voucher", icon: Gift, label: "قسيمة تاجر" }, { id: "money", icon: CircleDollarSign, label: "قيمة مالية" }
];

export default function LoyaltyExplainer() {
  const [selected, setSelected] = useState<EarnedValueKind>("points");
  const [defaultDestinationId, setDefaultDestinationId] = useState<DestinationId>("sense-points");
  const [temporaryDestinationId, setTemporaryDestinationId] = useState<DestinationId | null>(null);
  const [defaultPreferenceNotice, setDefaultPreferenceNotice] = useState<string | null>(null);
  const rule = earnedValueRules[selected];
  const destinationPreview = resolveDestination({ defaultDestinationId, askEachRedemption: false }, temporaryDestinationId ?? undefined);
  const chooseDefaultDestination = (requestedDestinationId: DestinationId) => {
    const result = saveDefaultDestination({ defaultDestinationId, askEachRedemption: false }, requestedDestinationId);
    setDefaultDestinationId(result.preference.defaultDestinationId);
    setDefaultPreferenceNotice(result.saved ? "تم اختيار نقاط SENSE كتفضيل افتراضي داخل النموذج." : "هذه الجهة معلقة ولا يمكن حفظها كتفضيل قبل اعتماد شراكة وواجهة مزود.");
  };
  return <main dir="rtl" className="min-h-screen bg-[#f4f6f2] text-[#163c3b]"><div className="mx-auto max-w-7xl px-5 pb-16 pt-5 lg:px-8">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#163c3b]/15 pb-5"><Link href={sensePortalHref} className="inline-flex items-center gap-3 font-extrabold hover:text-[#a87521]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#173f3c] text-[#f5ce75]"><BadgeCheck size={21} /></span><span><b className="block text-lg">SENSE / استحقاق</b><small className="text-[#58706a]">نموذج نقاط وقسائم قبل أي قيمة مالية</small></span></Link><span className="inline-flex items-center gap-2 rounded-xl border border-[#173f3c]/15 px-3 py-2 text-sm font-extrabold text-[#526c65]"><PhoneOff size={16} />لا يطلب رقم هاتف</span></header>
    <section className="grid gap-8 py-12 lg:grid-cols-[1.15fr_.85fr] lg:items-end"><div><p className="inline-flex rounded-full bg-[#e7cf99]/50 px-3 py-1.5 text-xs font-extrabold text-[#765617]">نموذج استحقاق مقيد</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-[1.16] sm:text-6xl">التقدير يمكن أن يبدأ كنقاط، <span className="text-[#a87521]">ولا يصبح رصيدًا نقديًا بالاسم فقط.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#527068]">يوضح هذا النموذج ما قد يستحقه مروج أو مزود عن نشاط موثق. لا يحفظ رقم هاتف، ولا ينشئ محفظة، ولا يرسل رصيدًا أو قسيمة.</p></div><aside className="rounded-[2rem] bg-[#173f3c] p-7 text-white"><LockKeyhole className="text-[#f5ce75]" size={23} /><h2 className="mt-5 text-2xl font-extrabold">القاعدة الأولى</h2><p className="mt-3 leading-7 text-[#c7ddd4]">ربط الهاتف لا يبدأ إلا بعد موافقة مستقلة، تحقق، عقد مزود، وسياسة تسوية وتشغيل.</p></aside></section>
    <section><p className="text-sm font-extrabold text-[#a87521]">01 · اختر نوع القيمة</p><h2 className="mt-1 text-3xl font-extrabold">ما الذي تريد بناءه فعلًا؟</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{options.map((option) => { const Icon = option.icon; const active = option.id === selected; return <button key={option.id} type="button" onClick={() => setSelected(option.id)} className={cn("min-h-44 rounded-[1.5rem] border p-5 text-right", active ? "border-[#a87521] bg-[#fff8e9]" : "border-[#173f3c]/15 bg-white hover:border-[#a87521]/60")}><Icon className={active ? "text-[#a87521]" : "text-[#55716a]"} size={23} /><h3 className="mt-6 text-xl font-extrabold">{option.label}</h3><p className="mt-2 text-sm leading-6 text-[#58716a]">{earnedValueRules[option.id].availability}</p></button>; })}</div></section>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-[1.7rem] border border-[#173f3c]/15 bg-white p-6"><p className="text-sm font-extrabold text-[#a87521]">الحالة الآن</p><h2 className="mt-2 text-3xl font-extrabold">{rule.title}</h2><p className="mt-4 leading-7 text-[#58716a]">{rule.availability}</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#e9f0e7] p-5"><h3 className="font-extrabold">يمكن تصميمه لاحقًا</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[#43645a]">{rule.allowed.map((item) => <li key={item}>• {item}</li>)}</ul></div><div className="rounded-2xl bg-[#fff0d7] p-5"><h3 className="font-extrabold">مغلق الآن</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[#765522]">{rule.blocked.map((item) => <li key={item}>• {item}</li>)}</ul></div></div></article><article className="rounded-[1.7rem] border border-[#173f3c]/15 bg-[#fdfcf6] p-6"><ShieldCheck className="text-[#a87521]" size={23} /><h2 className="mt-5 text-2xl font-extrabold">بوابة ربط الهاتف لاحقًا</h2><ol className="mt-4 space-y-3 text-sm leading-7 text-[#58716a]"><li><b>1.</b> برنامج ممول ومشغل محددان.</li><li><b>2.</b> موافقة صريحة على الغرض من الربط.</li><li><b>3.</b> تحقق لمرة واحدة من مزود معتمد.</li><li><b>4.</b> مرجع مزود أو بصمة مجزأة، لا رقم ظاهر في دفتر النقاط.</li><li><b>5.</b> تسوية وتدقيق واعتراض قبل أي قيمة مالية.</li></ol><a href="https://github.com/Solvanix/urban-sense-core/blob/main/docs/LOYALTY-AND-EARNED-VALUE-SAFETY-DESIGN-2026-08-23.md" target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-[#805c1b]">اقرأ عقد التشغيل الكامل <ArrowLeft size={16} /></a></article></section>
    <section className="mt-8 rounded-[1.7rem] border border-[#173f3c]/15 bg-white p-6"><p className="text-sm font-extrabold text-[#a87521]">02 · تفضيل وجهة الاستحقاق</p><h2 className="mt-2 text-3xl font-extrabold">احتفظ بتفضيلك، ثم غيّره مؤقتًا عند الحاجة.</h2><p className="mt-3 max-w-4xl leading-7 text-[#58716a]">هذا عرض لعقد التفضيل فقط. لا نطلب رقم حساب أو رقم بطاقة أو رقم هاتف، ولا تعني أسماء الجهات أدناه وجود ربط أو تحويل متاح معها.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{earnedValueDestinations.map((destination) => <button key={destination.id} type="button" onClick={() => chooseDefaultDestination(destination.id)} className={cn("rounded-2xl border p-4 text-right", defaultDestinationId === destination.id ? "border-[#a87521] bg-[#fff8e9]" : "border-[#173f3c]/15 hover:border-[#a87521]/50")}><b>{destination.label}</b><span className="mt-2 block text-sm text-[#58716a]">{destination.status}</span></button>)}</div>{defaultPreferenceNotice && <p className="mt-3 text-sm font-bold text-[#805c1b]">{defaultPreferenceNotice}</p>}<div className="mt-6 rounded-2xl bg-[#eef2e9] p-5"><p className="font-extrabold">اختيار مؤقت لاستحقاق واحد</p><div className="mt-3 flex flex-wrap gap-2">{earnedValueDestinations.map((destination) => <button key={destination.id} type="button" onClick={() => setTemporaryDestinationId(destination.id)} className={cn("rounded-xl border px-3 py-2 text-sm font-extrabold", temporaryDestinationId === destination.id ? "border-[#173f3c] bg-[#173f3c] text-white" : "border-[#173f3c]/20 text-[#35564f]")}>{destination.label}</button>)}<button type="button" onClick={() => setTemporaryDestinationId(null)} className="rounded-xl border border-[#173f3c]/20 px-3 py-2 text-sm font-extrabold text-[#35564f]">استخدم التفضيل الافتراضي</button></div><p className="mt-4 text-sm leading-7 text-[#43645a]">{destinationPreview.pendingApproval ? "الاختيار الذي طلبته معلّق: لا توجد شراكة أو واجهة معتمدة. يبقى النموذج على نقاط SENSE ولا يتغير تفضيلك الافتراضي." : "الاختيار الافتراضي في هذا النموذج هو نقاط SENSE غير النقدية فقط."}</p></div></section>
  </div></main>;
}
