import { refugeeContextSources, type RefugeeContextSource } from "@/lib/refugeeContext";
import { nationalContinuityHref, sensePortalHref, workCompassHref } from "@/lib/sensePortalRoute";
import { cn } from "@/lib/utils";
import { ArrowLeft, BookOpenCheck, CheckCircle2, ExternalLink, Landmark, MapPinned, ShieldCheck, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

type ContinuityNeed = "learning" | "access" | "memory" | "project";
type ContinuityCapability = "source" | "skill" | "coordination" | "archive";

const continuityNeeds: Array<{ id: ContinuityNeed; label: string; prompt: string; output: string }> = [
  { id: "learning", label: "تعلم أو عمل", prompt: "أريد أن أحول مهارة أو خبرة إلى مخرج قابل للنقل.", output: "مسار مهارة ومخرج عمل قصير" },
  { id: "access", label: "وصول وإتاحة", prompt: "أريد جعل المعلومة أو التجربة أو الأداة أوضح وأسهل وصولًا.", output: "دليل إتاحة أو خريطة روابط رسمية" },
  { id: "memory", label: "مكان وذاكرة", prompt: "أريد حفظ معنى مكان أو معرفة أو مسار تعليمي بمصدره وسياقه.", output: "بطاقة ذاكرة وسجل مصدر" },
  { id: "project", label: "مشروع محلي", prompt: "أريد جمع كفاءات حول حاجة ومخرج صغير قابل للتجربة.", output: "نطاق مشروع وفريق مراجعة أولي" },
];

const continuityCapabilities: Array<{ id: ContinuityCapability; label: string; detail: string }> = [
  { id: "source", label: "معرفة ومصدر", detail: "قراءة الوقائع بتاريخها ونطاقها وتحويلها إلى بطاقة معرفة قابلة للتحقق." },
  { id: "skill", label: "مهارة قابلة للنقل", detail: "تعلم عملي يخرج بملف عمل أو نموذج أو مهارة يستطيع الشخص تطويرها." },
  { id: "coordination", label: "تنسيق وإتاحة", detail: "تنظيم روابط ومعلومات عامة ومراجعة وصول من دون استقبال حالات أو بيانات حساسة." },
  { id: "archive", label: "ذاكرة وأرشيف", detail: "حفظ قرار أو مكان أو مسار معرفة مع المصدر والسياق وحق الاستخدام." },
];

export default function NationalContinuity() {
  const [need, setNeed] = useState<ContinuityNeed | null>(null);
  const [capability, setCapability] = useState<ContinuityCapability | null>(null);
  const [sourceId, setSourceId] = useState<RefugeeContextSource["id"]>("qalandia");
  const selectedSource = refugeeContextSources.find((source) => source.id === sourceId)!;
  const output = useMemo(() => need && capability ? { need: continuityNeeds.find((item) => item.id === need)!, capability: continuityCapabilities.find((item) => item.id === capability)! } : null, [need, capability]);

  return <main dir="rtl" className="min-h-screen bg-[#eef2e9] text-[#173b3a]"><div className="mx-auto max-w-7xl px-5 pb-16 pt-5 lg:px-8">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#173b3a]/15 pb-5"><Link href={sensePortalHref} className="inline-flex items-center gap-3 rounded-xl font-extrabold hover:text-[#95691f]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#173b3a] text-[#f5cd74]"><Landmark size={22} /></span><span><b className="block text-lg">SENSE / الاستمرارية الوطنية</b><small className="font-bold text-[#5b746d]">قدرة محلية · مهارة · معرفة · إتاحة · ذاكرة · مشروع</small></span></Link><span className="inline-flex items-center gap-2 rounded-xl border border-[#173b3a]/15 px-3 py-2 text-sm font-extrabold text-[#47645c]"><MapPinned size={16} />اقتراح تأسيسي قابل للبناء</span></header>
    <section className="grid gap-8 py-12 lg:grid-cols-[1.12fr_.88fr] lg:items-end"><div><p className="inline-flex rounded-full bg-[#e8cf98]/45 px-3 py-1.5 text-xs font-extrabold text-[#705019]">منظومة وطنية للقدرة المحلية</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-[1.14] tracking-tight sm:text-6xl">نحافظ على القدرة كي تبقى المعرفة والمهارة والمكان <span className="text-[#a87521]">قابلة للفعل.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#58716a]">يقترح SENSE مركزًا وطنيًا لتطوير المنظومات والقدرات المحلية: يجمع الكفاءات والمشاريع والمصادر والأرشيف والإتاحة في مخرجات يستطيع المجتمع البناء فوقها، من الفرد إلى الفريق إلى الشراكة المكتوبة.</p></div><aside className="rounded-[2rem] bg-[#173b3a] p-7 text-white"><h2 className="text-2xl font-extrabold">ما نطوره</h2><p className="mt-4 leading-7 text-[#c9ddd5]">دليل مصدر، مسار مهارة، خريطة إتاحة، بطاقة ذاكرة، ونطاق مشروع محلي. هذه أصول مدنية قابلة للتعلم والمراجعة والتوسع عبر شراكات صحيحة.</p></aside></section>
    <section><p className="text-sm font-extrabold text-[#a87521]">01 · حدد نقطة القدرة</p><h2 className="mt-1 text-3xl font-extrabold">ما الذي تريد أن يبقى قابلًا للتعلم أو الوصول أو البناء؟</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{continuityNeeds.map((item) => <button key={item.id} type="button" onClick={() => setNeed(item.id)} className={cn("min-h-52 rounded-[1.55rem] border p-5 text-right transition-colors", need === item.id ? "border-[#a87521] bg-[#fff8e9]" : "border-[#173b3a]/15 bg-white hover:border-[#a87521]/55")}><b className="text-xl">{item.label}</b><span className="mt-4 block text-sm leading-7 text-[#58716a]">{item.prompt}</span></button>)}</div></section>
    <section className="mt-8"><p className="text-sm font-extrabold text-[#a87521]">02 · اختر طبقة البناء</p><h2 className="mt-1 text-3xl font-extrabold">أي قدرة ستقود المخرج الأول؟</h2><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{continuityCapabilities.map((item) => <button key={item.id} type="button" onClick={() => setCapability(item.id)} className={cn("min-h-52 rounded-[1.55rem] border p-5 text-right transition-colors", capability === item.id ? "border-[#a87521] bg-[#fff8e9]" : "border-[#173b3a]/15 bg-white hover:border-[#a87521]/55")}><BookOpenCheck className="text-[#a87521]" size={22} /><b className="mt-5 block text-xl">{item.label}</b><span className="mt-3 block text-sm leading-7 text-[#58716a]">{item.detail}</span></button>)}</div></section>
    {output && <section className="mt-8 rounded-[2rem] border border-emerald-700/20 bg-[#e5f0e7] p-7 sm:p-9" aria-live="polite"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-extrabold text-[#8e651e]">مخرج أول قابل للتنفيذ</p><h2 className="mt-2 text-3xl font-extrabold">{output.need.output}</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-[#4d695f]">ابدأ من <b>{output.capability.label}</b>: {output.capability.detail}</p></div><CheckCircle2 className="text-emerald-700" size={31} /></div><div className="mt-7 grid gap-3 md:grid-cols-3"><p className="rounded-2xl bg-white/75 p-4 text-sm font-bold leading-6 text-[#466259]">حدد المصدر أو الحاجة والسياق.</p><p className="rounded-2xl bg-white/75 p-4 text-sm font-bold leading-6 text-[#466259]">سمِّ مالك المخرج ومراجع الجودة.</p><p className="rounded-2xl bg-white/75 p-4 text-sm font-bold leading-6 text-[#466259]">اختبره في نطاق صغير ثم وثّق التعلم.</p></div><div className="mt-6 flex flex-wrap gap-3"><Link href={workCompassHref} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#173b3a] px-4 text-sm font-extrabold text-white">ابنِ بطاقة العمل <ArrowLeft size={16} /></Link><a href={nationalContinuityHref} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#173b3a]/20 px-4 text-sm font-extrabold text-[#35574f]">رابط هذا المسار <ArrowLeft size={16} /></a></div></section>}
    <section className="mt-12 border-t border-[#173b3a]/15 pt-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-extrabold text-[#a87521]">مصادر تقود الفهم</p><h2 className="mt-1 text-3xl font-extrabold">من المصدر إلى مشروع معرفة أو مهارة أو إتاحة.</h2></div><p className="max-w-xl text-sm leading-6 text-[#58716a]">تُعرض هذه المصادر لقراءة الواقع كما هو، وتبقى تسمية العلاقة معها «مصدر عام» ما لم يوجد تفويض أو اتفاق مكتوب.</p></div><div className="mt-6 grid gap-4 md:grid-cols-3">{refugeeContextSources.map((source) => <button key={source.id} type="button" onClick={() => setSourceId(source.id)} className={cn("rounded-[1.5rem] border p-5 text-right", sourceId === source.id ? "border-[#a87521] bg-[#fff8e9]" : "border-[#173b3a]/15 bg-white hover:border-[#a87521]/55")}><b className="text-lg">{source.title}</b><span className="mt-3 block text-sm font-bold text-[#805c1b]">{source.updated}</span></button>)}</div><article className="mt-5 rounded-[1.7rem] border border-[#173b3a]/15 bg-white p-6"><h3 className="text-2xl font-extrabold">{selectedSource.title}</h3><p className="mt-4 max-w-4xl leading-8 text-[#58716a]">{selectedSource.summary}</p><a href={selectedSource.href} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 font-extrabold text-[#805c1b]">افتح المصدر الرسمي وتاريخه <ExternalLink size={16} /></a></article></section>
    <section className="mt-8 grid gap-4 md:grid-cols-3"><article className="rounded-[1.5rem] bg-[#173b3a] p-6 text-white"><ShieldCheck className="text-[#f5cd74]" size={22} /><h2 className="mt-5 text-xl font-extrabold">شراكة صحيحة</h2><p className="mt-3 leading-7 text-[#c9ddd5]">تبدأ العلاقة بمعرفة أو حوار أو تشاور، وتصبح شراكة عند وجود اتفاق مكتوب ونطاق واضح وموافقة مناسبة.</p></article><article className="rounded-[1.5rem] border border-[#173b3a]/15 bg-white p-6"><UsersRound className="text-[#a87521]" size={22} /><h2 className="mt-5 text-xl font-extrabold">قدرة المجتمع</h2><p className="mt-3 leading-7 text-[#58716a]">الفرد يتعلم ويخرج مخرجًا، والفريق يراجع ويبني، والشريك يفتح موردًا أو سياقًا أو تجربة محددة.</p></article><article className="rounded-[1.5rem] border border-[#173b3a]/15 bg-white p-6"><Landmark className="text-[#a87521]" size={22} /><h2 className="mt-5 text-xl font-extrabold">ملحق الحوكمة</h2><p className="mt-3 leading-7 text-[#58716a]">المنظومة لا تسجل مساعدات أو مستفيدين، ولا تدير إغاثة أو مرافق أو عمليات أممية. تبني أصول معرفة ومهارة وإتاحة في نطاق مدني مستقل.</p></article></section>
  </div></main>;
}
