import { refugeeContextGuards, refugeeContextSources, type RefugeeContextSource } from "@/lib/refugeeContext";
import { sensePortalHref } from "@/lib/sensePortalRoute";
import { cn } from "@/lib/utils";
import { ArrowLeft, BookOpenCheck, ExternalLink, HandHeart, Landmark, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const communityRoles = [
  { icon: BookOpenCheck, title: "معرفة مصدرية", description: "قراءة المعلومة الإنسانية مع تاريخها ومصدرها، وتجنب تحويلها إلى شائعة أو وعد خدمة." },
  { icon: UsersRound, title: "تعلم ومهارة مستقلة", description: "مسارات مهارة ومشاريع صغيرة ومساندة أقران لا تستخدم اسم الأونروا ولا موادها ولا بيانات المستفيدين." },
  { icon: HandHeart, title: "إحالة مسؤولة", description: "توجيه الشخص إلى صفحة الجهة الرسمية للمعلومة؛ لا نتلقى الطلب ولا نعد بالاستجابة." },
];

export default function RefugeeContext() {
  const [selectedId, setSelectedId] = useState<RefugeeContextSource["id"]>("gaza");
  const selected = refugeeContextSources.find((source) => source.id === selectedId)!;
  return <main dir="rtl" className="min-h-screen bg-[#f5f3ed] text-[#163c3b]"><div className="mx-auto max-w-7xl px-5 pb-16 pt-5 lg:px-8">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-[#173f3c]/15 pb-5"><Link href={sensePortalHref} className="inline-flex items-center gap-3 font-extrabold hover:text-[#a87521]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#173f3c] text-[#f5ce75]"><Landmark size={21} /></span><span><b className="block text-lg">SENSE / سياق اللاجئين</b><small className="text-[#58706a]">معرفة موثقة · إحالة رسمية · مهارات مستقلة</small></span></Link><span className="inline-flex items-center gap-2 rounded-xl border border-[#173f3c]/15 px-3 py-2 text-sm font-extrabold text-[#526c65]"><ShieldCheck size={16} />لا تسجيل ولا طلب مساعدة</span></header>
    <section className="grid gap-8 py-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="inline-flex rounded-full bg-[#e7cf99]/50 px-3 py-1.5 text-xs font-extrabold text-[#765617]">معرفة لا تحل محل الاستجابة الإنسانية</p><h1 className="mt-5 max-w-4xl text-4xl font-extrabold leading-[1.16] sm:text-6xl">دور المجتمع أن يحافظ على <span className="text-[#a87521]">المعنى والمهارة والإحالة الصحيحة.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#527068]">خدمات اللاجئين الإنسانية والتعليمية والصحية من مسؤولية الجهات المخولة، وفي مقدمتها الأونروا ضمن تفويضها. هذه الصفحة لا تنشئ خدمة موازية؛ تحفظ سياقًا موثقًا وتفتح مسار تعلم مستقلًا بلا بيانات مستفيدين.</p></div><aside className="rounded-[2rem] bg-[#173f3c] p-7 text-white"><ShieldCheck className="text-[#f5ce75]" size={23} /><h2 className="mt-5 text-2xl font-extrabold">حدودنا واضحة</h2><p className="mt-3 leading-7 text-[#c7ddd4]">لا نوزع مساعدات، لا ندير قوائم لاجئين، لا نجمع تبرعات، ولا نتحدث باسم الأونروا أو الأمم المتحدة.</p></aside></section>
    <section><p className="text-sm font-extrabold text-[#a87521]">01 · اختر سياقًا موثقًا</p><h2 className="mt-1 text-3xl font-extrabold">الخدمة قد تستمر، وقد تكون مقيدة في الوقت نفسه.</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{refugeeContextSources.map((source) => <button key={source.id} type="button" onClick={() => setSelectedId(source.id)} className={cn("min-h-44 rounded-[1.5rem] border p-5 text-right", selectedId === source.id ? "border-[#a87521] bg-[#fff8e9]" : "border-[#173f3c]/15 bg-white hover:border-[#a87521]/60")}><b className="text-xl">{source.title}</b><span className="mt-3 block text-sm font-bold text-[#805c1b]">{source.updated}</span></button>)}</div><article className="mt-5 rounded-[1.7rem] border border-[#173f3c]/15 bg-white p-6"><h3 className="text-2xl font-extrabold">{selected.title}</h3><p className="mt-4 max-w-4xl leading-8 text-[#58716a]">{selected.summary}</p><a href={selected.href} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 font-extrabold text-[#805c1b]">افتح المصدر الرسمي وتاريخه <ExternalLink size={16} /></a></article></section>
    <section className="mt-8 grid gap-4 md:grid-cols-3">{communityRoles.map((role) => { const Icon = role.icon; return <article key={role.title} className="rounded-[1.5rem] border border-[#173f3c]/15 bg-white p-6"><Icon className="text-[#a87521]" size={22} /><h2 className="mt-5 text-xl font-extrabold">{role.title}</h2><p className="mt-3 text-sm leading-7 text-[#58716a]">{role.description}</p></article>; })}</section>
    <section className="mt-8 rounded-[1.7rem] bg-[#e8eee4] p-6"><p className="text-sm font-extrabold text-[#a87521]">حواجز التشغيل</p><h2 className="mt-2 text-3xl font-extrabold">ما لن تفعله هذه الصفحة</h2><ul className="mt-5 grid gap-3 text-sm leading-7 text-[#43645a] md:grid-cols-2">{refugeeContextGuards.map((guard) => <li key={guard}>• {guard}</li>)}</ul><div className="mt-6 flex flex-wrap gap-4"><a href="https://github.com/Solvanix/urban-sense-core/blob/main/docs/research/QALANDIA-TRAINING-AND-JERUSALEM-AIRPORT-FACTS-2026-08-25.md" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-extrabold text-[#805c1b]">افتح سجل الحقائق والحدود <ArrowLeft size={16} /></a><a href="https://github.com/Solvanix/urban-sense-core/blob/main/docs/vision/SENSE-QALANDIA-CONTINUITY-VISION-2026-08-25.md" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-extrabold text-[#805c1b]">اقرأ رؤية الاستمرارية <ArrowLeft size={16} /></a></div></section>
  </div></main>;
}
