import assert from 'node:assert/strict';
import { createPilotStore, createMunicipalContext, authorizeMunicipalAction, issueMunicipalDemoCard, revokeMunicipalDemoCard, createDemoQrPayload, validateDemoQrPayload, queueMunicipalPilotEvent, syncPilotEvents, serialisePilotStore, restorePilotStore } from './maba-pilot.js';

const store = createPilotStore();
const baseNow = Date.parse('2030-09-18T00:00:00Z');
const operatorA = createMunicipalContext({ municipalityId: 'municipality-a', role: 'operator' });
const auditorA = createMunicipalContext({ municipalityId: 'municipality-a', role: 'auditor' });
const operatorB = createMunicipalContext({ municipalityId: 'municipality-b', role: 'operator' });
assert.equal(authorizeMunicipalAction(store, operatorA, { municipalityId: 'municipality-a' }).allowed, true);
assert.equal(authorizeMunicipalAction(store, operatorA, { municipalityId: 'municipality-b' }).reason, 'MUNICIPALITY_SCOPE_DENIED');
const card = issueMunicipalDemoCard(store, operatorA, { cardId: 'card-test-001', category: 'ACC' });
assert.equal(card.municipalityId, 'municipality-a');
assert.throws(() => revokeMunicipalDemoCard(store, operatorB, card.id), /MUNICIPALITY_SCOPE_DENIED/);
assert.throws(() => revokeMunicipalDemoCard(store, auditorA, card.id), /ACTION_NOT_ALLOWED/);
const qr = createDemoQrPayload(store, card.id, baseNow);
assert.equal(validateDemoQrPayload(store, qr, baseNow + 60_000).valid, true);
assert.equal(validateDemoQrPayload(store, { ...qr, municipalityId: 'municipality-b' }).reason, 'MUNICIPALITY_SCOPE_DENIED');
assert.equal(validateDemoQrPayload(store, { ...qr, signature: 'tampered' }).reason, 'SIGNATURE_MISMATCH');
assert.equal(validateDemoQrPayload(store, qr, baseNow + 6 * 60_000).reason, 'QR_EXPIRED');
const first = queueMunicipalPilotEvent(store, operatorA, { eventId: 'evt-001', type: 'demo.access.check', cardId: card.id, municipalityId: 'municipality-a' });
assert.deepEqual(first, { queued: true, duplicate: false });
assert.throws(() => queueMunicipalPilotEvent(store, operatorB, { eventId: 'evt-cross', type: 'demo.access.check', cardId: card.id, municipalityId: 'municipality-a' }), /MUNICIPALITY_SCOPE_DENIED/);
assert.deepEqual(queueMunicipalPilotEvent(store, operatorA, { eventId: 'evt-001', type: 'demo.access.check', cardId: card.id, municipalityId: 'municipality-a' }), { queued: false, duplicate: true });
assert.deepEqual(syncPilotEvents(store), { synced: ['evt-001'], rejected: [], remaining: 0 });
const restored = restorePilotStore(serialisePilotStore(store));
assert.equal(restored.acceptedEventIds.has('evt-001'), true);
assert.equal(restored.municipalities['municipality-a'].roles.includes('auditor'), true);
console.log('maba pilot checks: ok');
